version: 2
jobs: 
  build:
    docker:
      - image: "circleci/buildpack-deps"
    steps:
      - checkout
      - run: 
          name: Installing third party 
          command: 'cd Raytracer/Raytracer/third; make --linux-g++'
      - run:
          name: Build raytracer
          command: 'cd ..; make'
