version: 2
jobs: 
  build:
    docker:
      - image: "circleci/buildpack-deps"
    steps:
      - checkout
      - run: 
          name: Where are we
          command: 'pwd; ls'
      - run: 
          name: Installing third party 
          command: 'cd RayTracer/third/ann/; make linux-g++'
      - run:
          name: Build raytracer
          command: 'cd ..; cd ..; make'
